import React from "react";
import { Link } from "wouter";

export default function Terms() {
  return (
    <div className="min-h-screen bg-background text-foreground">
      <div className="max-w-3xl mx-auto px-6 py-12">
        <nav className="mb-8 text-sm">
          <Link href="/" className="text-muted-foreground hover:text-primary transition-colors">
            &larr; Back to GHS Label Maker
          </Link>
        </nav>

        <h1 className="text-3xl font-bold mb-2">Terms of Service</h1>
        <p className="text-sm text-muted-foreground mb-8">
          Last updated: April 14, 2026
        </p>

        <div className="prose prose-neutral dark:prose-invert max-w-none space-y-6 text-sm leading-relaxed">
          <section>
            <h2 className="text-xl font-semibold mt-8 mb-3">1. Acceptance of Terms</h2>
            <p>
              By accessing or using GHS Label Maker (ghs.txid.uk, "the Service"), you agree to be
              bound by these Terms of Service. If you do not agree with any part of these terms,
              please do not use the Service.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-semibold mt-8 mb-3">2. Description of Service</h2>
            <p>
              GHS Label Maker is an AI-assisted document processing tool that extracts hazard
              information from Safety Data Sheets (SDS/MSDS) in PDF format and generates formatted
              outputs including GHS hazard labels, dangerous goods transport labels, IATA
              Shipper's Declarations, 16-section GHS-compliant SDS documents, and UN38.3 battery
              test summary documents. The Service uses third-party large language models to
              assist with data extraction and formatting.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-semibold mt-8 mb-3">3. No Professional or Legal Advice</h2>
            <p className="font-semibold">
              The outputs produced by the Service are generated by artificial intelligence and
              must not be relied upon without independent review by a qualified safety
              professional. The Service does not provide legal, regulatory, or professional
              advice.
            </p>
            <p>
              Hazard labels, SDS documents, and transport declarations generated through the
              Service are provided as drafts for review. You are solely responsible for verifying
              the accuracy, completeness, and regulatory compliance of every document before
              using it for any commercial, shipping, storage, handling, or legal purpose. The
              Service operator accepts no liability for incorrect classification, missing
              information, misinterpretation of source documents, or any consequences arising
              from the use of AI-generated outputs.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-semibold mt-8 mb-3">4. Accounts and Authentication</h2>
            <p>
              The Service uses Lightning Network wallet authentication (LNURL-auth) provided by
              api.txid.uk. No email address, password, or personal information is required to
              create an account. Your account is identified solely by the public key derived from
              your Lightning wallet. You are responsible for keeping your wallet and its backup
              seed phrase secure.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-semibold mt-8 mb-3">5. Free Tier and Paid Credits</h2>
            <p>
              New users receive a limited number of free extractions. Beyond the free tier, use
              of the Service requires the purchase of credits. Credits may be purchased using
              Bitcoin Lightning Network payments or, where available, by card or other fiat
              payment methods processed through our third-party payment provider.
            </p>
            <p>
              Credits are non-transferable and have no cash value outside the Service. Time-based
              plans (weekly, monthly, annual) expire on the date indicated at purchase.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-semibold mt-8 mb-3">6. Refund Policy</h2>
            <p>
              Because credits enable immediate access to AI processing, all purchases are final
              once credits have been used. Unused credits purchased through a fiat payment
              processor may be refunded within 14 days of purchase, subject to the payment
              processor's rules and any applicable fees. Lightning Network payments are not
              refundable due to the irreversible nature of Bitcoin transactions. To request a
              refund, contact the operator using the address listed in section 13.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-semibold mt-8 mb-3">7. Acceptable Use</h2>
            <p>You agree not to:</p>
            <ul className="list-disc pl-6 space-y-1">
              <li>Upload documents you do not have the right to process</li>
              <li>Use the Service to generate fraudulent, misleading, or falsified safety documents</li>
              <li>Attempt to reverse engineer, scrape, overload, or disrupt the Service</li>
              <li>Share or resell credits, access tokens, or generated outputs in violation of applicable law</li>
              <li>Use the Service in any way that violates export controls or sanctions regimes</li>
            </ul>
          </section>

          <section>
            <h2 className="text-xl font-semibold mt-8 mb-3">8. Uploaded Content</h2>
            <p>
              You retain all rights to the PDF documents you upload. By uploading a document, you
              grant the operator a limited, non-exclusive license to process the document through
              the Service and its AI providers solely for the purpose of generating the output
              you request. Uploaded files are not used to train any AI model and are not shared
              with third parties other than the AI processing provider (see our Privacy Policy).
            </p>
          </section>

          <section>
            <h2 className="text-xl font-semibold mt-8 mb-3">9. Output History</h2>
            <p>
              Generated outputs are stored for thirty (30) days and are accessible to the account
              that generated them. After thirty days, records may be automatically deleted. You
              may request deletion of a specific output at any time.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-semibold mt-8 mb-3">10. Disclaimer of Warranties</h2>
            <p>
              The Service is provided on an "as is" and "as available" basis without warranties
              of any kind, either express or implied, including but not limited to warranties of
              merchantability, fitness for a particular purpose, non-infringement, or accuracy of
              AI-generated output. The operator does not warrant that the Service will be
              uninterrupted, error-free, or that any defects will be corrected.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-semibold mt-8 mb-3">11. Limitation of Liability</h2>
            <p>
              To the maximum extent permitted by applicable law, the operator shall not be liable
              for any indirect, incidental, special, consequential, or punitive damages, or any
              loss of profits, revenue, data, or business arising out of or related to your use
              of the Service, even if the operator has been advised of the possibility of such
              damages. The operator's total liability shall not exceed the amount paid by you for
              credits used in the ninety (90) days preceding the event giving rise to the claim.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-semibold mt-8 mb-3">12. Termination</h2>
            <p>
              The operator may suspend or terminate your access to the Service at any time,
              without notice, for conduct that violates these Terms or is harmful to other users,
              the operator, or third parties. You may stop using the Service at any time.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-semibold mt-8 mb-3">13. Contact and Governing Law</h2>
            <p>
              These Terms are governed by the laws of the Republic of Korea. Any dispute arising
              from or relating to the Service shall be resolved in the courts located in Seoul,
              Republic of Korea.
            </p>
            <p>
              For questions, refund requests, or legal notices, contact:{" "}
              <a href="mailto:admin@txid.uk" className="text-primary underline">
                admin@txid.uk
              </a>
            </p>
          </section>

          <section>
            <h2 className="text-xl font-semibold mt-8 mb-3">14. Changes to Terms</h2>
            <p>
              The operator may update these Terms from time to time. The "Last updated" date at
              the top of this page will reflect the most recent revision. Continued use of the
              Service after changes are posted constitutes acceptance of the updated Terms.
            </p>
          </section>
        </div>

        <div className="mt-12 pt-6 border-t text-xs text-muted-foreground flex gap-4">
          <Link href="/" className="hover:text-primary transition-colors">Home</Link>
          <Link href="/privacy" className="hover:text-primary transition-colors">Privacy Policy</Link>
        </div>
      </div>
    </div>
  );
}
