import React from "react";

interface DocumentViewProps {
  title: string;
  data: Record<string, unknown>;
  mode: string;
}

export function DocumentView({ title, data, mode }: DocumentViewProps) {
  const renderValue = (val: unknown): React.ReactNode => {
    if (val === null || val === undefined) return <span className="text-muted-foreground italic">N/A</span>;
    if (typeof val === "boolean") return val ? "Yes" : "No";
    if (Array.isArray(val)) {
      if (val.length === 0) return <span className="text-muted-foreground italic">None</span>;
      return (
        <ul className="list-disc pl-5 space-y-0.5">
          {val.map((v, i) => <li key={i}>{typeof v === "object" ? JSON.stringify(v) : String(v)}</li>)}
        </ul>
      );
    }
    if (typeof val === "object") return <pre className="text-xs bg-muted/50 p-2 rounded overflow-x-auto">{JSON.stringify(val, null, 2)}</pre>;
    return String(val);
  };

  const labelMap: Record<string, string> = {
    productName: "Product Name",
    unNumber: "UN Number",
    properShippingName: "Proper Shipping Name",
    hazardClass: "Hazard Class",
    subsidiaryRisks: "Subsidiary Risks",
    packingGroup: "Packing Group",
    marinePollutant: "Marine Pollutant",
    emergencyPhone: "Emergency Phone",
    supplier: "Supplier / Manufacturer",
    signalWord: "Signal Word",
    casNumber: "CAS Number",
    chemicalFormula: "Chemical Formula",
    hazardStatements: "Hazard Statements (H)",
    precautionaryStatements: "Precautionary Statements (P)",
    pictograms: "Pictograms",
    // DGD
    shippingName: "Shipping Name",
    packagingInstructions: "Packaging Instructions",
    quantity: "Quantity",
    authorization: "Authorization",
    additionalHandling: "Additional Handling",
    declarationText: "Declaration",
    // SDS
    sections: "Sections",
    // UN38.3
    testSummary: "Test Summary",
    manufacturer: "Manufacturer",
    batteryType: "Battery Type",
    wattHourRating: "Watt-hour Rating",
    lithiumContent: "Lithium Content",
    testResults: "Test Results",
    language: "Language",
    notRegulated: "Not Regulated",
  };

  const skipKeys = ["language"];
  const modeLabel: Record<string, string> = {
    dgd: "IATA Dangerous Goods Declaration",
    "sds-convert": "GHS Safety Data Sheet (16-Section)",
    un383: "UN38.3 Battery Transport Summary",
  };

  return (
    <div
      className="bg-white flex flex-col font-sans text-black"
      data-testid="ghs-label-container"
      style={{ width: 794, border: "6px solid #333", boxSizing: "border-box" }}
    >
      {/* Header */}
      <div style={{ borderBottom: "3px solid #333", padding: "16px 24px", backgroundColor: "#f5f5f5" }}>
        <div style={{ fontSize: 10, fontWeight: 700, color: "#888", textTransform: "uppercase", letterSpacing: "0.1em" }}>
          {modeLabel[mode] || title}
        </div>
        <h1 style={{ fontSize: 24, fontWeight: 900, margin: "4px 0 0", color: "#111" }}>
          {String(data.productName || data.shippingName || title)}
        </h1>
      </div>

      {/* Body */}
      <div style={{ padding: "16px 24px" }}>
        <table style={{ width: "100%", borderCollapse: "collapse", fontSize: 13 }}>
          <tbody>
            {Object.entries(data)
              .filter(([k]) => !skipKeys.includes(k))
              .map(([key, val]) => (
                <tr key={key} style={{ borderBottom: "1px solid #eee" }}>
                  <td style={{ padding: "8px 8px 8px 0", fontWeight: 700, color: "#555", width: "35%", verticalAlign: "top" }}>
                    {labelMap[key] || key.replace(/([A-Z])/g, " $1").replace(/^./, s => s.toUpperCase())}
                  </td>
                  <td style={{ padding: "8px 0", color: "#222" }}>
                    {renderValue(val)}
                  </td>
                </tr>
              ))}
          </tbody>
        </table>
      </div>

      {/* Footer */}
      <div style={{ padding: "10px 24px", backgroundColor: "#f5f5f5", borderTop: "2px solid #ddd", fontSize: 10, color: "#888", textAlign: "center" }}>
        Generated by ghs.txid.uk
      </div>
    </div>
  );
}
